
pipeline{
    agent any

    environment{

        AWS_CREDENTIALS= 'aws-ecr-credentials'

        BUILD_CONTEXT='./db'

        DATABASE_IMAGE_DEV= 'avejlanjekar45/employee-management-database-dev'
        DATABASE_IMAGE_QA= 'avejlanjekar45/employee-management-database-qa'
        DATABASE_IMAGE_UAT='avejlanjekar45/employee-management-database-uat'
        DATABASE_IMAGE_PROD='avejlanjekar45/employee-management-database-prod'

        REGISTRY_URL= 'https://registry.hub.docker.com'

        DEV_DH_CREDENTIALS= 'dockerhub-credentials'
        QA_DH_CREDENTIALS= 'dockerhub-credentials'
        UAT_DH_CREDENTIALS= 'dockerhub-credentials'
        PROD_DH_CREDENTIALS= 'dockerhub-credentials'

        CLUSTER_CREDENTIALS= 'eks-kubeconfig'

        AWS_REGION = 'ap-south-1'
        EKS_CLUSTER = 'employee-management-eks'

        DEV_NS= 'employee-dev'
        QA_NS= 'employee-qa'
        UAT_NS= 'employee-uat'
        PROD_NS= 'employee-prod'
    }

    parameters{
        choice(
            name: 'Environment',
            choices: ["dev","qa","uat","prod"],
            description: "Select deployment environment"
        )

        string(
            name: 'IMAGE_TAG',
            defaultValue: '',
            description: 'provide commit id'
        )
    }

    stages{

        stage("build & push"){
            when {
                expression{
                    params.Environment == "dev"
                }
            }
            steps{
                script{
                    buildAndPushImage("${env.DATABASE_IMAGE_DEV}","${env.DEV_DH_CREDENTIALS}","${env.BUILD_CONTEXT}")
                }
            }
        }

        
        stage("Dev- Deploy to eks"){
            when{
                expression{
                    params.Environment == "dev"
                }
            }

            steps{
                script{
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                            credentialsId: "${env.AWS_CREDENTIALS}"]
                    ]) {
                            deployToEks("${env.DEV_NS}", "${params.Environment}")
                    }
                }
            }
        }

        stage("promote image DEV to QA"){
            when{
                expression{
                    params.Environment == "qa"
                }
            }
            steps{
                script{

                    promoteImage("${env.DATABASE_IMAGE_DEV}","${env.DATABASE_IMAGE_QA}","${env.DEV_DH_CREDENTIALS}","${env.QA_DH_CREDENTIALS}")
                }
            }
        }

        stage("QA- Deploy to eks"){
            when{
                expression{
                    params.Environment == "qa"
                }
            }

            steps{
                script{
                    deployToEks("${env.QA_NS}","${params.Environment}")
                }
            }
        }

        stage("promote image QA to UAT"){
            when {
                expression{
                    params.Environment == "uat"
                }
            }
            steps{
                script{

                    promoteImage("${env.DATABASE_IMAGE_QA}","${env.DATABASE_IMAGE_UAT}", "${env.QA_DH_CREDENTIALS}","${env.UAT_DH_CREDENTIALS}")

                }
            }
        }

        stage("UAT- Deploy to eks"){
            when{
                expression{
                    params.Environment == "uat"
                }
            }

            steps{
                script{
                    deployToEks("${env.UAT_NS}","${params.Environment}")
                }
            }
        }

        stage("approval for prod"){
            when{
                expression{
                    params.Environment == 'prod'
                }
            }
            steps{
                input message: 'Promote the image from UAT to PROD?',
                      ok: "Promote to PROD"
            }
        }
        

        stage("Promote image from UAT to PROD"){
            when{
                expression{
                    params.Environment == "prod"
                }
            }
            steps{
                script{

                    promoteImage("${env.DATABASE_IMAGE_UAT}","${env.DATABASE_IMAGE_PROD}","${env.UAT_DH_CREDENTIALS}","${env.PROD_DH_CREDENTIALS}")
                }
            }
        }

        stage("PROD- Deploy to eks"){
            when{
                expression{
                    params.Environment == "prod"
                }
            }

            steps{
                script{
                    deployToEks("${env.PROD_NS}","${params.Environment}")
                }
            }
        }
    }
    post{
        always{
            deleteDir()
        }
    }
}

def buildAndPushImage(String DATABASE_IMAGE, String DH_CREDENTIALS, String Buildcontext){
    def database= docker.build("${DATABASE_IMAGE}:${GIT_COMMIT}","${Buildcontext}")

    docker.withRegistry("${env.REGISTRY_URL}","${DH_CREDENTIALS}"){
        database.push()
    }
}

def promoteImage(String sourceImage, String targetImage, String source_DH_Credentials, String target_DH_Credentials){
    docker.withRegistry("${env.REGISTRY_URL}","${source_DH_Credentials}"){
        docker.image("${sourceImage}:${params.IMAGE_TAG}").pull()
    }

    sh "docker tag ${sourceImage}:${params.IMAGE_TAG} ${targetImage}:${params.IMAGE_TAG}"

    docker.withRegistry("${env.REGISTRY_URL}","${target_DH_Credentials}"){
        docker.image("${targetImage}:${params.IMAGE_TAG}").push()
    }
}

def deployToEks(String namespace, String environment){
    sh "aws eks update-kubeconfig --region ${env.AWS_REGION} --name ${env.EKS_CLUSTER}"
    sh "kubectl create namespace ${namespace}"
    sh 'kubectl get nodes'
    
    if(params.Environment == "dev"){
        sh "echo deploying to ${namespace} namespace..."
        sh "sed -i -e 's/{{ENV}}/${environment}/g' -e 's/{{COMMITID}}/${env.GIT_COMMIT}/g' kube/mysql-deployment.yml "
    }else{
        sh "echo deploying to ${namespace} namespace..."
        sh "sed -i -e 's/{{ENV}}/${environment}/g' -e 's/{{COMMITID}}/${params.IMAGE_TAG}/g' kube/mysql-deployment.yml "
    }  

    sh "kubectl apply -f kube/configmap.yml -n ${namespace}"
    sh "kubectl apply -f kube/db-secret.yml -n ${namespace}"
    sh "kubectl apply -f kube/mysql-deployment.yml -n ${namespace}"
    sh "kubectl apply -f kube/mysql-service.yml -n ${namespace}"
    
}